### ISSUE TITLE
Text font size

### ISSUE THREAD

**Issue by andrii-pukhalevych** [raffaem/pdftools#1]
Is it possible to set font size for generated text?
And also use right/center align?

**Comment by raffaem** [comment]
You can specify a [LaTeX font size](https://www.overleaf.com/learn/latex/Font_sizes,_families,_and_styles#Reference_guide) directly before the text.

For example, the following adds today's date and page numbers in the pdf using a huge font size (notice the `\huge` option):

`pdftools --input-file ./pdfs/wikipedia_algorithm.pdf --output ./out/addtext.pdf --text "\huge $page/$pages" 0.95 0.97 --text "\huge $day/$month/$year" 0.01 0.01 --fitpaper --overwrite`

Not sure what do you mean by "also use right/center align". Can you clarify that please?

You can specify the text position directly in the command line.

**Comment by andrii-pukhalevych** [comment]
Thanks @raffaem. You should add this information to doc. For me it was not clear that text may include latext font size option.
right align is needed when page numbers are added to bottom right side of page. In this case its better to specify position of right corner bottom corner (1 1 for example). 0.95 0.97 will cause shifting if page numbers jumps over 10, 100 etc:
```
 1/999
 10/999
 100/999
```

As you can see last letter is not aligned well here and it will looks not very good.

**Comment by raffaem** [comment]
Hello,

in the syntax `--text text_string hpos vpos` I believe that `hpos` and `vpos` refers to the upper left corner of the text box that will contain the text. If you put `1 1` the upper right corner of the text box will be located at the bottom right corner of the page, and so no text will be displayed ... I don't know if I explained it right

Can you provide an example I can work on? Are you adding more than one text to the same page?

I will update the documentation.

Thank you again for your interest, Best

**Comment by raffaem** [comment]
Hello @andrii-pukhalevych ,

can you check whether, using the latest commit, the following command will add the page numbers in the way you want?

`python3 -m pdftools -if slides.pdf -o slidesout.pdf --fitpaper --overwrite --text "\$page/\$pages" br 1 1`

**Comment by andrii-pukhalevych** [comment]
br, tr - that exactly what I need.  
Now its awesome :1st_place_medal:

**Comment by andrii-pukhalevych** [comment]
Maybe you also know easy way to not add page number on first page if possible.
Now I concatenate conference proceedings (title + papers) with page numbers, then removing title and adding title without page number/

**Comment by andrii-pukhalevych** [comment]
Added pdftools link to conference website: http://itconf.nuos.edu.ua/2020/ and http://itconf.nuos.edu.ua/2021/
Its free IT internet conference in Ukraine.
Will delete this comment after closing issue

**Comment by raffaem** [comment]
> Maybe you also know easy way to not add page number on first page if possible.
> Now I concatenate conference proceedings (title + papers) with page numbers, then removing title and adding title without page number/

Hello again,

I think we have to reflect on it a bit because on don't think there is an easy feasible way to implement this.

pdftools use LaTeX pdfpages under the hood, and write the text on the pdf using the pdfpages package, calling calling a page style using the pagecommand option:

`\includepdf[keepaspectratio, pages={-},vfitpaper]{\detokenize{whiteslides.pdf}} `

```
\fancypagestyle{file0}{
	[...] <- initialization
	\begin{textblock*}{\textboxwidth}[1,1](1\paperwidth, 1\paperheight)
		\raggedright \thepage/\pageref{LastPage}
	\end{textblock*}
} %end of fancypagestyle
```

Doing what you suggest would require importing the pdf in two steps and having two different page styles on them, something like:

Importing the first page, no page style:
`\includepdf[keepaspectratio, pages={1},fitpaper]{\detokenize{whiteslides.pdf}} `

Importing all the other pages, with the page style to write page numbers:
`\includepdf[keepaspectratio, pages={2-},pagecommand=\thispagestyle{file0},fitpaper]{\detokenize{whiteslides.pdf}} `



> Added pdftools link to conference website: http://itconf.nuos.edu.ua/2020/ and http://itconf.nuos.edu.ua/2021/
> Its free IT internet conference in Ukraine.
> Will delete this comment after closing issue

Thank you so much for the endorsement :)

**Comment by raffaem** [comment]
> Maybe you also know easy way to not add page number on first page if possible.

Closed as not implemented for now
