### ISSUE TITLE
pdftools require Python 3, you are using Python

### ISSUE THREAD

**Issue by noloader** [raffaem/pdftools#2]
Hi Everyone,

I'm trying to add page numbers to a PDF per [How to add page numbers to Postscript/PDF](https://stackoverflow.com/a/61922298).

I used Wget to fetch `pdftools` and `pdftools.py`. They are in PWD with the files I want to modify.

Running `pdftools.py --check-latex` results in:

```bash
$  ./pdftools.py --check-latex
import-im6.q16: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/408.
./pdftools.py: line 3: syntax error near unexpected token `'pdftools require Python 3, you are using Python ''
./pdftools.py: line 3: `    print('pdftools require Python 3, you are using Python ' + '.'.join(str(x) for x in sys.version_info[:3]))'
```

I'm not a Python person, so I can't help much with the Python3 problems. About all I know is Python3 is installed:

```bash
$ sudo apt-get install python3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3 is already the newest version (3.8.2-0ubuntu2).
```

And:

```bash
$ command -v python3
/usr/bin/python3
```
The error messages don't make much sense to me. It would probably be helpful to tell the user what to do next.

**Comment by raffaem** [comment]
1. Can you post all the output of running just `python`

2. Can you try running the program with `python3  ./pdftools.py --check-latex`

**Comment by noloader** [comment]
It looks like the source file is missing a shebang...

```diff
--- pdftools.py
+++ pdftools.py
@@ -1,3 +1,5 @@
+#!/usr/bin/env python3
+
 import sys
 if sys.version_info[0] < 3:
     print('pdftools require Python 3, you are using Python ' + '.'.join(str(x) for x in sys.version_info[:3]))
```

And a quick touchup. On the BSDs, Bash is *not* located at `/bin/bash`. It is located at `/usr/local/bin/bash`.

```diff
--- pdftools
+++ pdftool
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 # see https://stackoverflow.com/questions/59895/how-to-get-the-source-directory-of-a-bash-script-from-within-the-script-itself
 
```

`/usr/bin/env` is Posix, so it is portable. It should not break either script.

**Comment by noloader** [comment]
Are you sure [this](https://stackoverflow.com/a/61922298) actually works:

```bash
pdftools --input-file input.pdf --output output.pdf --text $page/$pages 0.9 0.9 --fitpaper
```

I keep getting an error:

```bash
usage: pdftools.py [-h] [-if INPUT_FILES] [-id INPUT_DIRS]
                   [-o OUTPUT | --out-suffix OUT_SUFFIX] [--paper PAPER_TYPE]
                   [--scale SCALE_FACTOR] [--width WIDTH] [--height HEIGHT]
                   [--nup ROWS COLS] [--offset RIGHT TOP]
                   [--trim Left Bottom Right Top] [--delta X Y]
                   [--custom CUSTOM] [--pages PAGES]
                   [-t text_string anchor hpos vpos] [--text-help]
                   [--extract-pages file_name] [--natural-sorting]
                   [--overwrite] [--open] [--white-page] [--repair]
                   [--check-latex] [--split-pages] [--swap-pages]
                   [--last-page-even] [--clip] [--landscape] [--frame]
pdftools.py: error: argument -t/--text: expected 4 arguments
```

**Comment by noloader** [comment]
I'm going to find another way to add page numbers. This is not working out on Ubuntu 20.

Thanks for the help.

**Comment by raffaem** [comment]
@noloader Hello,

The info on StackOverflow is outdated. The CLI changed  a little since then.

There is a new option to specify the anchor point of the text box which you want to position.

The correct example for you is this:

`pdftools --input-file ./pdfs/wikipedia_algorithm.pdf --output ./out/addtext.pdf --text "\huge $page/$pages" tl 0.95 0.97 --text "\huge $day/$month/$year" tl 0.01 0.01 --fitpaper --overwrite`

Please see the file in `examples/addtext.bat`

Relevant here is the section about the `-t` about in the help:

```
-t text_string anchor hpos vpos, --text text_string anchor hpos vpos
                        Add text to pdf file. 'text_string' is the string to
                        add, special variables can be passed, as well as LaTeX
                        font sizes like \Huge. Call --text-help for help on
                        how to build this string. 'anchor' is the point of the
                        text box (the box surrounding the text) to position:
                        'tl' will position the top-left corner, 'tr' will
                        position the top-right corner, 'bl' will position the
                        bottom-left corner, 'br' will position the bottom-
                        right corner, all other parameters are invalid. 'hpos'
                        and 'vpos' are numbers between 0 and 1 that represent
                        how far is 'anchor' from the top left corner of the
                        page. (default: None)
```

I am going to update the README.md and that StackOverflow post.

I am also going to add your suggestion for the base environment

**Comment by raffaem** [comment]
> Are you sure [this](https://stackoverflow.com/a/61922298) actually works:
> 
> ```shell
> pdftools --input-file input.pdf --output output.pdf --text $page/$pages 0.9 0.9 --fitpaper
> ```
> 
> I keep getting an error:
> 
> ```shell
> usage: pdftools.py [-h] [-if INPUT_FILES] [-id INPUT_DIRS]
>                    [-o OUTPUT | --out-suffix OUT_SUFFIX] [--paper PAPER_TYPE]
>                    [--scale SCALE_FACTOR] [--width WIDTH] [--height HEIGHT]
>                    [--nup ROWS COLS] [--offset RIGHT TOP]
>                    [--trim Left Bottom Right Top] [--delta X Y]
>                    [--custom CUSTOM] [--pages PAGES]
>                    [-t text_string anchor hpos vpos] [--text-help]
>                    [--extract-pages file_name] [--natural-sorting]
>                    [--overwrite] [--open] [--white-page] [--repair]
>                    [--check-latex] [--split-pages] [--swap-pages]
>                    [--last-page-even] [--clip] [--landscape] [--frame]
> pdftools.py: error: argument -t/--text: expected 4 arguments
> ```
> 
> When I add an empty argument for `anchor` (what is an anchor?):
> 
> ```shell
> pdftools ... --text '$page/$pages' '""' 0.95 0.95 --fitpaper
> ```
> 
> I get another error:

This is taken from `pdftools --help`:

```
'anchor' is the point of the text box (the box surrounding the text) to position: 'tl' will position the top-left corner, 'tr' will position the top-right corner, 'bl' will position the bottom-left corner, 'br' will position the bottom-right corner, all other parameters are invalid.
```

So the anchor specify the point of the text box to position. An empty anchor is not a valid option.

**Comment by raffaem** [comment]
Hello,

On Ubuntu you have to escape the `$` sign in the shell.

So the actual correct example for you is this:

`pdftools --input-file ./input/wikipedia_algorithm.pdf --output ./output/addtext.pdf --text "\$page/\$pages" br 1 1 --overwrite`

As you can see from the screenshot, it is working. I am on Ubuntu 20.10

![image](https://user-images.githubusercontent.com/54762742/105652590-e6daed00-5eb9-11eb-8e1b-c58524d1eff1.png)

**Comment by raffaem** [comment]
Hello,

I have updated and successfully tested all the examples on Ubuntu 20.10

Please call `pdftools.py` directly:

`pdftools.py .....`

The shebang will call the correct interpreter. 

There are no wrapper bash scripts anymore as they break when we pass float arguments.

Notice also that the `--fitpaper` option does not exist anymore as it is now the default.

**Comment by raffaem** [comment]
Reopen this if you need additional support.

All the exmaples work on Ubuntu 20.10 here, including adding page numbers.
