### ISSUE TITLE
Cannot find pdfsak after installation

### ISSUE THREAD

**Issue by anotatta** [raffaem/pdftools#4]
I try to install using pip on windows (python 3.9) and also on WSL ubuntu (python 3.8) .
On both setup, the system cannot find pdfsak.  

windows cmd: 'pdfsak' is not recognized as an internal or external command, operable program or batch file.
WSL ubuntu: -bash: /mnt/c/Python39/Scripts/pdfsak: C:\Python39\python.exe^M: bad interpreter: No such file or directory

**Comment by raffaem** [comment]
> I try to install using pip on windows (python 3.9) and also on WSL ubuntu (python 3.8) . On both setup, the system cannot find pdfsak.
> 
> windows cmd: 'pdfsak' is not recognized as an internal or external command, operable program or batch file. WSL ubuntu: -bash: /mnt/c/Python39/Scripts/pdfsak: C:\Python39\python.exe^M: bad interpreter: No such file or directory

Hello,

thank you very much for reporting this.

I am able to reproduce it, and a fix is on its way.

In the meantime you can use the version directly from the repository:
```
git clone https://github.com/raffaem/pdftools
cd pdftools
```

In the new `pdftools` folder you can find the `pdfsak` Python script, which you can call directly

**Comment by raffaem** [comment]
Hello,

the error on Windows should be fixed now.

Can you try to update pdfsak and retry?
```
pip3 install --upgrade pdfsak
```

Then we will tackle the one on WSL which is a different error

**Comment by raffaem** [comment]
Hello,

> windows cmd: 'pdfsak' is not recognized as an internal or external command, operable program or batch file.

This should be fixed for good now.

Can you try to run the following command on Windows Terminal and post the result, please?
```
pip3 install --upgrade pdfsak
pdfsak --version
```

> WSL ubuntu: -bash: /mnt/c/Python39/Scripts/pdfsak: C:\Python39\python.exe^M: bad interpreter: No such file or directory

Next we will tackle this, which is a different error

**Comment by anotatta** [comment]
pdfsak is recognized now on Windows.
I got a run time error which is not related to this.
I'll open another issue.

**Comment by raffaem** [comment]
> pdfsak is recognized now on Windows. I got a run time error which is not related to this. I'll open another issue.

Thanks.

Can you check on WSL, so we can close this?

**Comment by anotatta** [comment]
Works fine also on WSL.  I'm closing this.
Thx.
