### ISSUE TITLE
undefinedfilename error

### ISSUE THREAD

**Issue by anotatta** [raffaem/pdftools#6]
Hello

I run the following on windows:

pdfsak -if in.pdf -o out --clearscan

I got the following error (it looks like the full path name is missing windows path seperator "\"):
Traceback (most recent call last):
  File "C:\Python39\Scripts\pdfsak", line 876, in <module>
    main(sys.argv[1:])
  File "C:\Python39\Scripts\pdfsak", line 820, in main
    page_count = getPageCount(fp2)
  File "C:\Python39\Scripts\pdfsak", line 61, in getPageCount
    p = int(p)
ValueError: invalid literal for int() with base 10: 'Error: /undefinedfilename in --file--\nOperand stack:\n   (C:UsersAdminAppDataLocalTemppdfsakc_d6tcekin.pdf)   (r)\nExecution stack:\n   %interp_exit   .runexec2   --nostringval--   --nostringval--

**Comment by raffaem** [comment]
Can you run the following command and post the result?

```
gs -q -dNOSAFER -dNODISPLAY -c '(in.pdf) (r) file runpdfbegin pdfpagecount = quit'
```

**Comment by anotatta** [comment]
========================================================
Using single quote:
gs -q -dNOSAFER -dNODISPLAY -c '(in.pdf) (r) file runpdfbegin pdfpagecount = quit'
Error: /undefined in '
Operand stack:

Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--
Dictionary stack:
   --dict:738/1123(ro)(G)--   --dict:0/20(G)--   --dict:75/200(L)--
Current allocation mode is local
Last OS error: No such file or directory
GPL Ghostscript 9.54.0: Unrecoverable error, exit code 1

========================================================
Using double quote
 gs -q -dNOSAFER -dNODISPLAY -c "(in.pdf) (r) file runpdfbegin pdfpagecount = quit"
1

**Comment by raffaem** [comment]
Can you uninstall pdfsak:
```
pip3 uninstall pdfsak
```

Install it from latest commit:
```
git clone https://github.com/raffaem/pdftools
cd pdftools
python3 setup.py install --user
```

Re-run your initial command:
```
pdfsak -if in.pdf -o out --clearscan
```

And post the output?

**Comment by anotatta** [comment]
Could not find pdfsak again.  But when run directly 
 C:\Users\Admin\AppData\Roaming\Python\Python39\Scripts\pdfsak.bat -if in.pdf -o out.pdf -
-clearscan

Got this error:
ERROR: Cannot get page count.
cmd: ['gs', '-q', '-dNOSAFER', '-dNODISPLAY', '-c', '"(C:\\Users\\Admin\\AppData\\Local\\Temp\\pdfsakfs5zjk8q\\in.pdf) (r) file runpdfbegin pdfpagecount = quit"']
stdout: Error: /undefinedfilename in --file--
Operand stack:
   (C:UsersAdminAppDataLocalTemppdfsakfs5zjk8qin.pdf)   (r)
Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--
Dictionary stack:
   --dict:738/1123(ro)(G)--   --dict:0/20(G)--   --dict:75/200(L)--
Current allocation mode is local
Last OS error: No such file or directory

stderr: GPL Ghostscript 9.54.0: Unrecoverable error, exit code 1

===========================================
There are also a lot of pdfsak temp directories in  C:\Users\Admin\AppData\Local\Temp\
All of them have the in.pdf or other pdf file I tried.

**Comment by raffaem** [comment]
> Could not find pdfsak again

Sorry, the latest command I posted was wrong.

You must not install with `--user` on Windows, otherwise the script will not be in path.

As for the original issue, can you check whether the latest commit fix it?

Uninstall pdfsak once more:

```
pip3 uninstall pdfsak
```

Then (this time the install command is correct):

```
git clone https://github.com/raffaem/pdftools
cd pdftools
python3 setup.py install
```

Now pdfsak should at least be in path, and hopefully the issue is fixed as well

**Comment by raffaem** [comment]
Hello,

there are several bugs when running pdfsak on Windows.

I'm working  on it, will let you know when it's ready.

Thank you for your patience and thank you again for reporting.

**Comment by raffaem** [comment]
Hello,

pdfsak should now be fully compatible with Windows.

Can you check that this is fixed on the latest commit?

**Comment by anotatta** [comment]
It seems the installation is ok now.
There is still some runtime error in Windows.
